function lambda_val = lambdaFA
%LAMBDAFA
%    LAMBDA_VAL = LAMBDAFA

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    14-Nov-2019 01:56:58

%FA Constraints
lambda_val = -4.9e+1./5.0;
