function A_dot = A_acc
%A_ACC
%    A_DOT = A_ACC

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    14-Nov-2019 01:56:57

%Position Constraints
A_dot = reshape([0.0,0.0,2.0,0.0,0.0,2.0],[3,2]);
