function a = a_pos(x,y)
%A_POS
%    A = A_POS(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    14-Nov-2019 01:56:57

%Position Constraints
a = [y;x+y+1.0;(x-2.0).^2+(y-1.0).^2-2.0];
