function A = A_vel(x,y)
%A_VEL
%    A = A_VEL(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    14-Nov-2019 01:56:57

%Velocity Constraints
A = reshape([0.0,1.0,x.*2.0-4.0,1.0,1.0,y.*2.0-2.0],[3,2]);
